# C++ 008

### std::cerr

標準エラーを出力することが出来る  
そのため、標準出力では受け取れないため、 `2>` を使って受け取ることが出来る

`std::cout` を使って、エラー発生箇所を確認するのもいいが、エラー用途として使っていないものと混ざってしまうので、`std::err` だけででバック用として使うほうがいいだろう
